### ISSUE TITLE
Is the glog dependency excessive?

### ISSUE THREAD

**Issue by JeffAbrahamson** [ua-parser/uap-cpp#10]
It seems that the glog dependency exists only to provide `CHECK()`.  Perhaps those could be replaced with `assert` from `assert.h` in order to simplify the dependency requirements?

**Comment by asuhan** [comment]
@JeffAbrahamson I'll have a look at this and a few other things in 1-2 weeks. You have a point, that dependency should be optional at the very least.

**Comment by asuhan** [comment]
Fixed by bc411cafda81fe559d6adfc7696887c131eb6441.
