### ISSUE TITLE
Makefile explicitly sets CFLAGS and LDFLAGS

### ISSUE THREAD

**Issue by JeffAbrahamson** [ua-parser/uap-cpp#11]
Typically, these flags are available to the Makefile user in order to provide system-specific information.  I don't see another override mechanism.

In my case, for example, I want to set -std=c++14 so that I generate a library compatible with my other code.  And gtest should be installed per-library (says the gtest instructions now), so I need to provide -L gtest in order to find the library.

I can offer a patch, but there are so many ways to do it, I think I should ask what makes sense to you, first.  My inclination (and I'm not an expert) is to do something like this for each of CC, CFLAGS, and LDFLAGS:

    ifdef $(CFLAGS)
    MCFLAGS=$(CFLAGS)
    else
    MCFLAGS=-std=c++0x -Wall -Werror -g -O3
    fi

**Comment by asuhan** [comment]
@JeffAbrahamson Yes, I'll look into reasonable ways of doing this in a few days. Thanks!
