### ISSUE TITLE
Unexpected `os_v3_replacement` in test

### ISSUE THREAD

**Issue by JeffAbrahamson** [ua-parser/uap-cpp#12]
In [regexes.yaml, line 905](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml#L905), the key `os_v3_replacement` causes an exception at line 99 of [UaParser.cpp](https://github.com/asuhan/uap-cpp/blob/master/UaParser.cpp#L99) when running `make test`.

I'm not completely certain whether uap-core should change or uap-cpp, though I suspect uap-cpp of simply trailing uap-core.

**Comment by JeffAbrahamson** [comment]
Based on the uap-python tests, I'm pretty sure the uap-cpp tests are just trailing the yaml file.  I'll try to swing back to this with a patch, but I can't just now.

**Comment by asuhan** [comment]
@JeffAbrahamson A patch would be great, especially if you can keep it small. I plan to make this project work with the latest yaml file from upstream in a few days and merge the old pull requests as well, so we have to keep an eye on conflicts.

**Comment by asuhan** [comment]
@JeffAbrahamson Fixed, now it works with the upstream `uap-core` tests.
