### ISSUE TITLE
Compiling on Windows [Mingw]

### ISSUE THREAD

**Issue by alexsilva** [ua-parser/uap-cpp#13]
I use the IDE Clion configured with Mingw.

Disregarding lot of work that has to compile the project had the following problem:

```
`...\ua-parser\uap-cpp\UaParser.cpp: In function 'void {anonymous}::mark_placeholders({anonymous}::i2tuple&, const string&)':
...\ua-parser\uap-cpp\UaParser.cpp:41:28: error: 'stoi' is not a member of 'std'
     replacement_map[loc] = std::stoi(device_property.substr(loc + 1, 1));
                            ^
mingw32-make.exe[3]: *** [CMakeFiles/ua_parser.dir/uap-cpp/UaParser.cpp.obj] Error 1
```

Searching the internet I could do the work using the following alternative to [stoi](https://github.com/ua-parser/uap-cpp/blob/master/UaParser.cpp#L40)
```
replacement_map[loc] = (unsigned int) strtol(device_property.substr(loc + 1, 1).c_str(), 0, 1);
``` 

Not sure it is correct but it is working. Even setting the compiler flag (-std=c++11), the function does not exist in windows.

There is a better way to solve the above problem ?

**Comment by asuhan** [comment]
I think it should work now.
