### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by sursu** [ua-parser/uap-cpp#15]
Is it possible to determine whether the agent uses a mobile or PC? I see the D implementation has also `agent.isMobile`. 

It would be cool to have also the following attributes (from [python-user-agents](https://github.com/selwin/python-user-agents)):

- `is_tablet`: whether user agent is identified as a tablet device (iPad, Kindle Fire, Nexus 7 etc) 
- `is_pc`: whether user agent is identified to be running a traditional "desktop" OS (Windows, OS X, Linux)
- `is_touch`_capable: whether user agent has touch capabilities

`uagent.isSpider()` as I understand answers the question whether the agent is a web crawler/spider.

**Comment by asuhan** [comment]
Porting the logic from D shouldn't be too hard. I might have a look this w/e, unless you want to submit a patch yourself.

**Comment by asuhan** [comment]
Fixed by https://github.com/ua-parser/uap-cpp/pull/16.
