### ISSUE TITLE
Speed Issues

### ISSUE THREAD

**Issue by sursu** [ua-parser/uap-cpp#19]
The implementation is relatively slow.
Still faster than Python, but not by orders of magnitude.

I ran a test with 1mln instances and it completed in ~700 seconds.
For this test I demanded all the information to the extracted:
```
		UA[i][0] = uagent.browser.family;
		UA[i][1] = uagent.browser.major;
		UA[i][2] = uagent.browser.minor;
		UA[i][3] = uagent.browser.patch;
		UA[i][4] = uagent.browser.toString();
		UA[i][5] = uagent.browser.toVersionString();

		UA[i][6] = uagent.os.family;
		UA[i][7] = uagent.os.major;
		UA[i][8] = uagent.os.minor;
		UA[i][9] = uagent.os.patch;
		UA[i][10] = uagent.os.toString();
		UA[i][11] = uagent.os.toVersionString();

		UA[i][12] = uagent.toFullString();

		UA[i][13] = uagent.device.family;
		UA[i][14] = uagent.device.brand;
		UA[i][15] = uagent.device.model;
```

Alex, you mentioned previously that you used this parser for billions of data points. You clearly did not use all the fields, but how much  did it take approximately to parse a million examples? 

---

I can help with a multi-threaded implementation using thread pools. But, is there a way to optimize the inner code?

**Comment by asuhan** [comment]
I'm not surprised it's not a lot faster than the Python version; most of the work happens in the regex matching, which I'm pretty sure it's a C extension in Python as well. Also, I'd compare with an without the `toString()` and `toVersionString()`, those are definitely expensive.

At scale, two things helped: multi-threading and the fact that just a fraction of the data points contained user agent information.

Adding multi-threading to this library itself doesn't sound like a good idea, the callers can easily take care of it as they see fit. For serial optimization, I'd try other regex implementations (pcre for example) and then profiling the non-regex part, maybe it's something to improve there as well.
