### ISSUE TITLE
thread safe

### ISSUE THREAD

**Issue by catcoding123** [ua-parser/uap-cpp#20]
hi， your parser code is thread-safe？

**Comment by asuhan** [comment]
Should be, as long as you're linking against a thread-aware Boost build: https://www.boost.org/doc/libs/1_66_0/libs/regex/doc/html/boost_regex/background/thread_safety.html.

Would be nice to add a multi-threaded test with TSAN enabled.

**Comment by asuhan** [comment]
Added multi-threaded tests, ran them successfully with TSAN + Clang 6.0.0.
