### ISSUE TITLE
uap_core dependency

### ISSUE THREAD

**Issue by JeffAbrahamson** [ua-parser/uap-cpp#21]
In order for uap_cpp's tests to pass, the contents of uap_core must exist in the uap_core directory.  This can be done by copying that repo, separately cloned, or by cloning it as a submodule.

Either way, the README doesn't mention this.

I leave to you your preferred advice, but mentioning this in the README will save each newcomer a few minutes of debugging.

**Comment by asuhan** [comment]
The "Dependencies" section mentions it:

"uap-core, same directory level as uap-cpp. You can clone this repo with --recurse-submodules to get it."

However, if it could be made more obvious, I'm all for it. Thoughts?
