### ISSUE TITLE
Support MSVC to build the project

### ISSUE THREAD

**Issue by hsluoyz** [ua-parser/uap-cpp#23]
Currently, the project is using makefile to build, which is only available on Linux. Can we support to use MSVC (Visual Studio) to build it? Thanks,

**Comment by asuhan** [comment]
I'd like to, but I don't have easy access to MSVC / Windows. Contribution is welcome!

**Comment by hsluoyz** [comment]
I have made a PR here: https://github.com/ua-parser/uap-cpp/pull/24. Please review.

**Comment by hsluoyz** [comment]
I have made a PR here: https://github.com/ua-parser/uap-cpp/pull/24. Please review.

**Comment by hsluoyz** [comment]
I have made a PR here: https://github.com/ua-parser/uap-cpp/pull/24. Please review.

**Comment by hsluoyz** [comment]
I have made a PR here: https://github.com/ua-parser/uap-cpp/pull/24. Please review.
