### ISSUE TITLE
Replace boost-regex with Hyperscan to speed up 40x

### ISSUE THREAD

**Issue by hsluoyz** [ua-parser/uap-cpp#25]
The performance of ua-parser on 5 languages (including uap-cpp) is as follows:

![image](https://user-images.githubusercontent.com/3787410/57196059-a459da00-6f8b-11e9-82a2-def668847fa0.png)

* test_ua.yaml is test cases for Agent, only Agent is parsed.
* test_os.yaml is test cases for OS, only OS is parsed.
* test_device.yaml is test cases for Device, only Device is parsed.
* pgts_browser_list.yaml is test cases for all fields: (Agent, OS, Device). All three fields are parsed.

Compiler environments:
* C#: .NET 4.6
* Python: 3.6.8
* Java: Oracle JDK 1.8.0_191
* Go: 1.12
* C++: gcc 5.4.0

CPU: Intel Core i7-8750H 2.20GHz, 1 core

The conclusion is that uap-cpp is not much faster than other languages like Python (only 2x). As a common sense, C++ is at least 30x faster than Python.

The reason why uap-cpp is slower than expectation is because it uses boost-regex, which is a very slow regex matching library. I think we should use Intel's [Hyperscan](https://github.com/intel/hyperscan) as the regex library for uap-cpp to accelerate the speed.

Boost-regex is nearly the same speed as PCRE referred to [here](https://www.boost.org/doc/libs/1_52_0/libs/regex/doc/vc71-performance.html), and Hyperscan is 40x faster than PCRE referred to [here](https://rust-leipzig.github.io/regex/2017/03/28/comparison-of-regex-engines/#timings). So I roughly believe using Hyperscan in uap-cpp can speed up 40x. Can we support Hyperscan?

**Comment by asuhan** [comment]
C++ is not going to be 30x faster than Python for workloads which are regex parsing. Python's `re` module is written in C. If all we're doing is regex, we're comparing two C++ or C regex implementations, not the languages themselves. The main reason for having C++ bindings was not performance, but ease of integration with a C++ codebase. The measurement reveals that all mainstream languages have a high performance regex module, which is to be expected. Also, there's a relatively limited number of distinct UA strings we're going to see in real life, when I had to do this I simply added a cache and the hit rate was very high.

That being said, using a different regex engine is perfectly fine if it has all the features (syntax support and captures), is better than `boost::regex` and has decent support. I will look into it at some point, although I would take "up to 40x" claims with a big pinch of salt. Most likely we're going to see a mixed bag, hopefully better on average.

**Comment by asuhan** [comment]
Also, feel free to experiment with Hyperscan and send a PR. As long as the tests pass and it's faster, no reason we wouldn't switch.

**Comment by asuhan** [comment]
We got a ~10x speedup thanks to @DailyMats work, I think we can be pretty happy with the speed.

**Comment by hsluoyz** [comment]
Hi @asuhan @DailyMats  , thanks for the work! Which commit/PR contains this speedup? What commit should I use?

**Comment by asuhan** [comment]
Latest master contains all the required changes, https://github.com/ua-parser/uap-cpp/pull/26 added the improvements.
