### ISSUE TITLE
Tablet Device Types found for Mobile Devices

### ISSUE THREAD

**Issue by M4040** [ua-parser/uap-cpp#28]
Method :
```DeviceType UserAgentParser::device_type(const std::string& ua)```
is returning Tablet when the User Agent is for a Mobile eg with User Agent 

> Mozilla/5.0 (Linux; Android 8.0.0; SAMSUNG SM-J330FN Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/7.2 Chrome/11.1.1111.111 Mobile Safari/537.36

The regex used seem fine but the tablet regex seems very open with any android (case insensitive) match with an open wildcard. The Mobile check is more restrictive, so perhaps it should check for Mobiles first before returning rather than checking for the Tablets first as it is now. i.e.
```    try
    {
        if (rx_mob.match(ua, m) && m.get(2).find("mobile") == std::string::npos)
        {
            return uap_cpp::DeviceType::kMobile;
        }
        else if (rx_tabl.match(ua, m))
        {
            return uap_cpp::DeviceType::kTablet;
        }
        return uap_cpp::DeviceType::kDesktop;
    }
    catch (...)
    {
        return uap_cpp::DeviceType::kUnknown;
    }
```
Just an opinion

**Comment by asuhan** [comment]
Your example should be fixed now, I've also added it to the test. The recent switch from `boost::regex` to `re2` broke this.
