### ISSUE TITLE
gcc (GCC) 4.8.5 can't works

### ISSUE THREAD

**Issue by mtimebombm** [ua-parser/uap-cpp#29]
[root@localhost uap-cpp-master]# make uaparser_cpp
g++ -c  -std=c++14 -Wall -Werror -g -fPIC -O3 UaParser.cpp -o UaParser.o
g++: error: unrecognized command line option ‘-std=c++14’
make: *** [UaParser.o] Error 1

**Comment by asuhan** [comment]
Please pull from master and try again, it should work now - let me know the result.

**Comment by mtimebombm** [comment]
@asuhan   done, thank you very much!

[root@localhost uap-cpp-master]# make uaparser_cpp
g++ -c  -std=c++0x -Wall -Werror -g -fPIC -O3 UaParser.cpp -o UaParser.o
g++ -c  -std=c++0x -Wall -Werror -g -fPIC -O3 internal/Pattern.cpp -o internal/Pattern.o
g++ -c  -std=c++0x -Wall -Werror -g -fPIC -O3 internal/AlternativeExpander.cpp -o internal/AlternativeExpander.o
g++ -c  -std=c++0x -Wall -Werror -g -fPIC -O3 internal/SnippetIndex.cpp -o internal/SnippetIndex.o
g++ -c  -std=c++0x -Wall -Werror -g -fPIC -O3 internal/ReplaceTemplate.cpp -o internal/ReplaceTemplate.o
ar rcs libuaparser_cpp.a UaParser.o internal/Pattern.o internal/AlternativeExpander.o internal/SnippetIndex.o internal/ReplaceTemplate.o
[root@localhost uap-cpp-master]# make test
g++ -c  -std=c++0x -Wall -Werror -g -fPIC -O3 UaParserTest.cpp -o UaParserTest.o
g++ libuaparser_cpp.a UaParserTest.o -o UaParserTest libuaparser_cpp.a -lre2 -lyaml-cpp -lgtest -lpthread
./UaParserTest
[==========] Running 15 tests from 7 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from UserAgentParser
[ RUN      ] UserAgentParser.basic
[       OK ] UserAgentParser.basic (1 ms)
[ RUN      ] UserAgentParser.DeviceTypeMobile
[       OK ] UserAgentParser.DeviceTypeMobile (0 ms)
[ RUN      ] UserAgentParser.DeviceTypeTablet
[       OK ] UserAgentParser.DeviceTypeTablet (0 ms)
[ RUN      ] UserAgentParser.DeviceTypeDesktop
[       OK ] UserAgentParser.DeviceTypeDesktop (0 ms)
[----------] 4 tests from UserAgentParser (1 ms total)

[----------] 3 tests from OsVersion
[ RUN      ] OsVersion.test_os
[       OK ] OsVersion.test_os (79 ms)
[ RUN      ] OsVersion.test_ua
[       OK ] OsVersion.test_ua (223 ms)
[ RUN      ] OsVersion.additional_os_tests
[       OK ] OsVersion.additional_os_tests (11 ms)
[----------] 3 tests from OsVersion (313 ms total)

[----------] 4 tests from BrowserVersion
[ RUN      ] BrowserVersion.firefox_user_agent_strings
[       OK ] BrowserVersion.firefox_user_agent_strings (25 ms)
[ RUN      ] BrowserVersion.opera_mini_user_agent_strings
[       OK ] BrowserVersion.opera_mini_user_agent_strings (19 ms)
[ RUN      ] BrowserVersion.pgts_browser_list
[       OK ] BrowserVersion.pgts_browser_list (1210 ms)
[ RUN      ] BrowserVersion.podcasting_user_agent_strings
[       OK ] BrowserVersion.podcasting_user_agent_strings (39 ms)
[----------] 4 tests from BrowserVersion (1294 ms total)

[----------] 1 test from DeviceFamily
[ RUN      ] DeviceFamily.test_device
[       OK ] DeviceFamily.test_device (2265 ms)
[----------] 1 test from DeviceFamily (2266 ms total)

[----------] 1 test from SnippetIndex
[ RUN      ] SnippetIndex.snippets
[       OK ] SnippetIndex.snippets (13 ms)
[----------] 1 test from SnippetIndex (13 ms total)

[----------] 1 test from AlternativeExpander
[ RUN      ] AlternativeExpander.expansions
[       OK ] AlternativeExpander.expansions (0 ms)
[----------] 1 test from AlternativeExpander (0 ms total)

[----------] 1 test from ReplaceTemplate
[ RUN      ] ReplaceTemplate.expansions
[       OK ] ReplaceTemplate.expansions (0 ms)
[----------] 1 test from ReplaceTemplate (0 ms total)

[----------] Global test environment tear-down
[==========] 15 tests from 7 test cases ran. (3888 ms total)
[  PASSED  ] 15 tests.
[root@localhost uap-cpp-master]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by asuhan** [comment]
Fixed by fa58038a096461af2586c666d6fe3af3a41f4e11.
