### ISSUE TITLE
Compiling issue on Mac

### ISSUE THREAD

**Issue by IssacLam** [ua-parser/uap-cpp#3]
Hi, thanks for your effort to this library. I would like to use it with my application but, unlucky, I get the following error message when I try to compile the library. What should I do? I have install boost and yaml already. Thanks for your help.

pc-221-115:uap-cpp-master IssacLam$ make
g++ -c -std=c++0x -Wall -Werror -g -O3 UaParser.cpp -o UaParser.o -lboost_regex -lboost_system -lyaml-cpp -lglog
clang: error: -lboost_regex: 'linker' input unused
clang: error: -lboost_system: 'linker' input unused
clang: error: -lyaml-cpp: 'linker' input unused
clang: error: -lglog: 'linker' input unused
make: *** [UaParser.o] Error 1

**Comment by asuhan** [comment]
Should be fixed by 2a980b213082894523aaf7a55e96ee62a34063a1.
