### ISSUE TITLE
undefined reference to `re2::RE2::~RE2()'

### ISSUE THREAD

**Issue by sangyx** [ua-parser/uap-cpp#34]
I used uap-cpp in my project:
```bash
link_directories("3rd/lib") # 
...
include_directories("3rd/uap-cpp")
...
target_link_libraries(${BINARY} PUBLIC gtest libuaparser_cpp.a nlohmann_json::nlohmann_json)
```

And it caused an error:
```bash
lib/libuaparser_cpp.a(UaParser.o): In function `uap_cpp::UserAgentParser::~UserAgentParser()':
/usr/include/c++/7/bits/unique_ptr.h:78: undefined reference to `re2::RE2::~RE2()'
```

I have run `make test` in uap-cpp and it run all testcases successfully.

**Comment by asuhan** [comment]
Add `-lre2 -lyaml-cpp` to your link flags or use `libuaparser_cpp.so` instead. Have a look at `Makefile` and how `LDFLAGS` is used, you need to do the same.
