### ISSUE TITLE
make test fail

### ISSUE THREAD

**Issue by sibiyes** [ua-parser/uap-cpp#5]
Hi,

When I try "make test" it fails giving the following error

WARNING: Logging before InitGoogleLogging() is written to STDERR
F0708 21:48:43.950477 28953 UaParser.cpp:50] Check failed: in_stream.good() 
*** Check failure stack trace: ***
make: *** [test] Aborted (core dumped)

However the make test is successful when I run it for c++ version in https://github.com/tobie/ua-parser/tree/master/cpp

I believe both are the same code. How could one fail and the other pass the test

**Comment by asuhan** [comment]
@sibiyes: The tests require some *.yaml files:

https://github.com/tobie/ua-parser/blob/master/cpp/UaParserTest.cpp#L10
https://github.com/tobie/ua-parser/blob/master/cpp/UaParserTest.cpp#L88
https://github.com/tobie/ua-parser/blob/master/cpp/UaParserTest.cpp#L92
https://github.com/tobie/ua-parser/blob/master/cpp/UaParserTest.cpp#L96
https://github.com/tobie/ua-parser/blob/master/cpp/UaParserTest.cpp#L100
https://github.com/tobie/ua-parser/blob/master/cpp/UaParserTest.cpp#L104
https://github.com/tobie/ua-parser/blob/master/cpp/UaParserTest.cpp#L108

You can just copy them from `https://github.com/tobie/ua-parser/blob/master/regexes.yaml`, `https://github.com/tobie/ua-parser/tree/master/test_resources/*.yaml` and adjust the paths (or simply replicate the directory structure). We should make `https://github.com/ua-parser/uap-core` a sub-module of this repository.

**Comment by sibiyes** [comment]
@asuhan That make sense.

I just ignored the testing for now. 

So I created a shared library after running "make uaparser_cpp". But I am not able to include the header in an other script where I plan to use this. 

#include <UaParser.h> returns an error stating 

fatal error: UaParser.h: No such file or directory

Any idea what is the proper header to include ?

**Comment by asuhan** [comment]
@sibiyes: `UaParser.h` is the right header to include, it's probably not in your include path. The makefile doesn't copy it to the system include paths.
