### ISSUE TITLE
compile basic code 

### ISSUE THREAD

**Issue by spammenot66** [ua-parser/uap-cpp#6]
how do i compile in visual studio? I've download boost and yaml 0.3 and am trying to compile 
just main.cpp but I'm getting an error. Can someone provide some instructions on how to to compile uap-cpp in visual studio 2010? 

Thanks 
Newbie

**Comment by asuhan** [comment]
@spammenot66: `main.cpp` is part of a different library. At the time I've submitted my C++ pull request, there was another one pending and we ended up with two overlapping libraries in the same repository. Nevertheless, you should be able to build `UaParser.cpp` and use it in your project as a library, as long as you also link against yaml, boost and glog. I don't have any experience with Visual Studio 2010 (or Windows, in general), let me know if you get it working.
