### ISSUE TITLE
Compilation fails on unknown GetNextDocument

### ISSUE THREAD

**Issue by JeffAbrahamson** [ua-parser/uap-cpp#9]
This could as easily be a bug in the README if I am using incorrect libraries.  I assume it is enough (on ubuntu) to install libyaml-cpp-dev and libyaml-cpp0.5v5 (0.5.2-2), which I believe to be the same as this [yaml-cpp](https://github.com/jbeder/yaml-cpp) repository.  But none of those `YAML::Parser` classes have a `GetNextDocument` method.

    make -k
    g++ -c -std=c++0x -Wall -Werror -g -O3 UaParser.cpp -o UaParser.o -lboost_regex -lboost_system -lyaml-cpp -lglog
    In file included from UaParser.cpp:9:0:
    UaParser.cpp: In constructor ‘{anonymous}::UAStore::UAStore(const string&)’:
    UaParser.cpp:54:23: error: ‘class YAML::Parser’ has no member named ‘GetNextDocument’
	 CHECK(yaml_parser.GetNextDocument(regexes));
			   ^
    UaParser.cpp:30:34: error: ‘class YAML::detail::iterator_base<const YAML::detail::iterator_value>’ has no member named ‘first’
	   const std::string key = it.first().to<std::string>();              \
				      ^
    UaParser.cpp:59:7: note: in expansion of macro ‘FILL_AGENT_STORE’
	   FILL_AGENT_STORE(user_agent, browser, "family_replacement",
	   ^
    ...

**Comment by asuhan** [comment]
@JeffAbrahamson This repo is out of date and it's using the 0.3 API (check the README). This is the repo I have commit access to: https://github.com/asuhan/uap-cpp.

**Comment by JeffAbrahamson** [comment]
Ah, wow, that would have been hard to self-discover. ;-)  Thanks for the pointer.

I'll be happy to dismantle the python UserAgent server that I wrote to work around this.

Have you submitted a pull request to fix that here?  What would be the right pull request (to update the code here or instead to update the readme)?  @elsigh @tobie

**Comment by asuhan** [comment]
There's a pull request for this and other things here: https://github.com/ua-parser/uap-cpp/pull/4. I've also removed the dependency to glog in my fork, as you've suggested. I'm happy to fix issues as you report them, but can't guarantee they'll make it back to this repo.

**Comment by tobie** [comment]
@asuhan gave you commit access to this repo. LMK if you need anything else from me.

**Comment by asuhan** [comment]
@tobie Thanks!

**Comment by asuhan** [comment]
Fixed by dfadfed792724dd05c995934aed4c9f4d4b5c8f4.
